version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Check directory and list files
          command: pwd && ls -al
      - run:
          name: Create a zip of the build files
          command: bash ../deploy.sh
      - store_artifacts:
          path: build.zip
          destination: chrome-extension-build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: bash ../deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only: main
