version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    working_directory: ~/TeamMessenger
    executor: node/default
    steps:
      - checkout
      - run:
          name: Ensure permissions for deploy.sh
          command: chmod +x ./deploy.sh
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Compress build files (Brotli)
          command: npm run compress
      - run:
          name: Check directory and list files
          command: pwd && ls -al
      - run:
          name: Create a zip of the build files
          command: bash ./deploy.sh
      - store_artifacts:
          path: build.zip
          destination: chrome-extension-build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only: main
